/*Find the Difference
Solved
Easy
Topics
Companies
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"*/
class Solution {
    public char findTheDifference(String s, String t) {
       HashMap<Character,Integer>map=new HashMap<>();
       for(char ch:s.toCharArray()){
        map.put(ch,map.getOrDefault(ch,0)+1);
       }
       for(char ch:t.toCharArray()){
        if(!map.containsKey(ch) || map.get(ch)==0){
            return ch;
        }
        else{
            map.put(ch,map.get(ch)-1);
        }
       }
       return ' ';
    }
}
